### ISSUE TITLE
Sort collection by recently added

### ISSUE THREAD

**Issue by mandosocca** [slavabogov/cci-features#12]
**Is your feature request related to a problem? Please describe.**
Many collectors show their most recently added caps on their website. This feature would make that possible for all linked CCI collections.

**Describe the solution you'd like**
Simply include the new sorting possibility "recently added".

**Describe alternatives you've considered**
None. 

**Additional context**
None.

**Comment by slavabogov** [comment]
Two conditions when we can enable this sort order:

1. User is defined
2. Show caps is "In collection"

**Comment by slavabogov** [comment]
<img width="801" alt="Screenshot 2021-02-03 at 01 09 54" src="https://user-images.githubusercontent.com/7432004/106674861-afa4c400-65bc-11eb-8a6f-c9b5736584b2.png">
