### ISSUE TITLE
Enable possibility to hide sets from picture search

### ISSUE THREAD

**Issue by kubo8** [slavabogov/cci-features#23]
With the new giant picture sets (the one from Finland, the many US like pelliconi or black/white...) now the picture search is monopolised by those caps and make longer any research.
It would be great to have the chance to build something similar to a button like “exclude sets”.

**Comment by mudanepp** [comment]
Exclusion all types expect “bottle closure” would do the work. I’d prefer such exclusion at whole database level, not just for picture search. E.g. view at Bulgarian caps is really ruined by several fake series. A switch somewhere in the corner? An user preference to show/hide crap?

The Finnish Finn Korkki series should be classified as factory crowns or home use crowns.

**Comment by kubo8** [comment]
I don't agree.The goal is to exclude big quantity of caps that are always attributable to big sets. Not to used or not sued on bottles.
And the Finnish set, at least for now, should be left as "beer" category, as used on bottles.
    Il lunedì 7 dicembre 2020, 19:20:51 CET, Hannes Pehlak <notifications@github.com> ha scritto:  
 
 


Exclusion all types expect “bottle closure” would do the work. I’d prefer such exclusion at whole database level, not just for picture search. E.g. view at Bulgarian caps is really ruined by several fake series. A switch somewhere in the corner? An user preference to show/hide crap?

The Finnish Finn Korkki series should be classified as factory crowns or home use crowns.

**Comment by slavabogov** [comment]
@kubo8 done
