### ISSUE TITLE
Possibility to sort the logbook by editor

### ISSUE THREAD

**Issue by mandosocca** [slavabogov/cci-features#3]
**Is your feature request related to a problem? Please describe.**
I think it would be a good idea to add the possibility to sort the logbook entries by editor. In that way we could find the "editor of the month" by edited things.

**Describe the solution you'd like**
Simply create that sorting possibility.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by slavabogov** [comment]
Decided to implement only API access without UI
