### ISSUE TITLE
Public trade lists

### ISSUE THREAD

**Issue by mudanepp** [slavabogov/cci-features#34]
At the moment it is possible to see another person's trade and wanted caps either one by one, or through a link he/she has shared?

Trade list(s?) (and wanted list?) of other collectors could be public and possible to browse (as Collection is already). Others lists could remain private (needs link to access).

**Comment by slavabogov** [comment]
@mudanepp I've implemented the list selector, so you can browse all other user's lists. Is this solving the issue?

<img width="1075" alt="Screenshot 2021-03-07 at 10 20 38" src="https://user-images.githubusercontent.com/7432004/110233738-c6796600-7f2e-11eb-9de8-541dfd820099.png">

**Comment by mudanepp** [comment]
> @mudanepp I've implemented the list selector, so you can browse all other user's lists. Is this solving the issue?

Yes!
