### ISSUE TITLE
View collection by the beverage type (beer / non-beer)

### ISSUE THREAD

**Issue by mihailoRS** [slavabogov/cci-features#43]
Sometime it would be convenient to view collection by the beverage type (beer / non-beer). This feature already exists in Stats when counting caps, where you can choose to count those two types separately. Now it would be great if you can view them separately as well.

**Comment by slavabogov** [comment]
Can be achieved using Advanced search. Is it ok?
<img width="760" alt="Screenshot 2022-12-16 at 18 44 11-min" src="https://user-images.githubusercontent.com/7432004/208147404-2defc2f5-7133-46ec-b269-a5c302602b89.png">

**Comment by mihailoRS** [comment]
OK. Thank you very much.

Sincerely yours,

Mihailo Alić,

http://crowncaps.info/collections/4946
http://www.ultrahome.in.rs/crowncaps/chronology/
