### ISSUE TITLE
Advanced search - City of the Producer

### ISSUE THREAD

**Issue by RennoCap** [slavabogov/cci-features#46]
Can it made possible to search on the city of the producer in advanced search?

**Comment by slavabogov** [comment]
It is already possible:

![image](https://user-images.githubusercontent.com/7432004/150689064-072a111f-d349-4add-ad52-4d0e699ddc4e.jpeg)

**Comment by RennoCap** [comment]
Thanks!

Verstuurd vanaf mijn iPhone
