### ISSUE TITLE
Show only caps not in personal collection from a list

### ISSUE THREAD

**Issue by kubo8** [slavabogov/cci-features#49]
Lists are used very often for showing doubles.
When a collector has hundreds of doubles added to a list and I want to check the caps I may miss, it would be way quicker to hide caps already linked into my collection. And eventually in addition also show only specific products (only beer, only soft drink...).
In that way I could save a lot of time but not going through hundreds of pages.

**Comment by slavabogov** [comment]
@kubo8 The feature is implemented. Now we can filter caps in any list
<img width="811" alt="Screenshot 2023-10-10 at 14 31 37" src="https://github.com/slavabogov/cci-features/assets/7432004/e400ead2-4e52-4d4d-9cab-d97ee435ade0">
