### ISSUE TITLE
 2 choices for Period Used  (release- and end date) 

### ISSUE THREAD

**Issue by 22-15** [slavabogov/cci-features#50]
Can we please change the button Period Used ? The period chosen is in maybe 90% of the cases not correct. I run in to this a lot of times when working for the USA catalog. my suggestion is that we change 1961 - 1970 into " 1960's and that we can choose two decades. ( sometimes it happens that a plastic cap is dated from 1961 - 1970 (cork period)) For instance a temporarely millenium cap that is used only one year in 2000 is dated 1991. (jubilee caps!) or a 2001 cap is dated 2010.
Or that we can choose the Periods more presicely. The suggestion to combine issued and Period used is also a good idea, but sometimes we only know a date of production or an expiring date (stamps)
Any change would be welcome to me personally because sometimes I read issued 1935 (end of prohibition) and period used 1931-1940. while in reality the cap was only used from 1935-1937 (producer bankrupt). Many times the button is not used so searching for caps from a period has little use then.

**Comment by slavabogov** [comment]
We can merge "Issued" and "Period used" into single "Year" field. It should inherit features from both fields, so it should be flexible.

The prototype of editing form (inspired by Geni interface):

<img width="594" alt="Screenshot 2023-03-18 at 00 33 04" src="https://user-images.githubusercontent.com/7432004/226064470-4eb18852-e72f-43ea-84b3-e1e76c85b0f1.png">

<details><summary>Possibility to select year with options "Exact", "Before", "After", "Between"</summary>
<img width="596" alt="Screenshot 2023-03-18 at 00 34 14" src="https://user-images.githubusercontent.com/7432004/226064532-75118283-c80b-490c-ab13-b9b27dd1b114.png">
</details> 

<details><summary>"Between" option has two year fields</summary>
<img width="597" alt="Screenshot 2023-03-18 at 00 33 45" src="https://user-images.githubusercontent.com/7432004/226064677-b92c5c87-dcc6-4709-bcf4-781b47307444.png">
</details> 

Every year can be marked as "Circa" to indicate approximate year.

On cap page it can be shown like this:

**Exact**
Year: 1910
Year: ±1910 (for Russian localization)
Year: circa 1919 (for English localization)

**Between**
Year: between 1910 and 1920

**Comment by 22-15** [comment]
Okay Dmitry, Thank you very much for the changes.
