### ISSUE TITLE
Search caps without info of factory sign section

### ISSUE THREAD

**Issue by bernat90** [slavabogov/cci-features#51]
Hello, in the advanced search I think it's good idea to include a option to search only crown caps without info in the factory sign section.
It's good option to search the factory sign of that caps and include to catalog.

**Comment by slavabogov** [comment]
We have section for providing missing info called "Unknown crown caps". My proposal to use it like this:

<img width="979" alt="Screenshot 2023-03-17 at 23 21 45" src="https://user-images.githubusercontent.com/7432004/226055756-f23017c1-c193-41d2-83f9-e84e41688c2d.png">

**Comment by bernat90** [comment]
> We have section for providing missing info called "Unknown crown caps". My proposal to use it like this:
> 
> <img alt="Screenshot 2023-03-17 at 23 21 45" width="979" src="https://user-images.githubusercontent.com/7432004/226055756-f23017c1-c193-41d2-83f9-e84e41688c2d.png">

I think it's good idea, all "unkown" info in the same section

**Comment by bernat90** [comment]
I think it's good idea, all "unkown" info in the same section

Enviat des de l'Outlook per a l'Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bernat90** [comment]
Closed that means that improvement are activated or are pending to create?

**Comment by slavabogov** [comment]
@bernat90 it was developed, but not yet deployed. Now it is deployed so you can check the result: https://crowncaps.info/caps/unknown
