### ISSUE TITLE
Information alert for solved caps

### ISSUE THREAD

**Issue by mandosocca** [slavabogov/cci-features#8]
**Is your feature request related to a problem? Please describe.**
It happens regularly that someone solves unknown caps without posting it in the corrections section on Davides Forum.

**Describe the solution you'd like**
Give a message alert to the creator and all linkers ("owners") of the unknown entry. 

**Describe alternatives you've considered**
None,

**Additional context**
None.

**Comment by slavabogov** [comment]
Can be done in scope of https://github.com/slavabogov/cci-features/issues/47 - user can subscribe to cap updates and receive notification
